### ISSUE TITLE
Transcript error is raised

### ISSUE THREAD

**Issue by Soham7777777** [Vihaan-Yagnik/pyhton-video-to-summary#1]
![Screenshot from 2024-05-25 15-10-26](https://github.com/Vihaan-Yagnik/pyhton-video-to-summary/assets/105550538/1b7b16cc-ca6d-45d6-8301-cf279fd08794)

If you can give a little overview of how the code works then I can contribute to solve the issue.

**Comment by Vihaan-Yagnik** [comment]
Thank you for raising the issue I certainly handled the exception in my last commit , and yes i will explain you the code in person.
